version: '3.7'

services:
  frontend:
    container_name: frontend
    depends_on:
      - testchain
    build:
      context: ./
    command: >
      sh -c "sleep 15 &&
             cd contract &&
             truffle migrate &&
             mkdir -p ../client/src/contracts &&
             cp -R build/contracts/* ../client/src/contracts/ &&
             cd ../client &&
             npm start"
    ports:
      - 3000:3000
  
  testchain:
    container_name: testchain
    image: trufflesuite/ganache-cli:latest
    command: --gasLimit 67219750
    ports:
      - 8545:8545
